{
 "title": "Python_Sample_Application",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"my-observability-service-5f54dbdf44-dmcjn\"} * 1000"
    }
   ]
  },
  {
   "title": "Total HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{endpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used By The Application",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(process_resident_memory_bytes{job=\"my-observability-service\"})\n/\nsum(kube_pod_container_resource_limits{namespace=\"default\", container=\"app\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service=\"my-observability-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"my-observability-service\", instance=\"172.31.65.14:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 *\nsum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"app\", pod=~\"my-observability-service.*\"}[5m]))\n/\nsum(kube_pod_container_resource_limits{namespace=\"default\", container=\"app\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 *\nsum(rate(process_cpu_seconds_total{job=\"my-observability-service\"}[5m]))\n/\n0.5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Reliability",
   "type": "stat",
   "description": "If in 5 minutes you have 900 successful requests\nand 100 failed/error requests the reliablity is:\n900 / 1000 * 100 = 90%",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(http_requests_total{service=\"my-observability-service\", status=~\"2..\"}[5m]))\n/\nsum(rate(http_requests_total{service=\"my-observability-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Shows how many requests each endpoint handled in the last hour.",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"my-observability-service\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Error Count (4XX+5XX)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{service=\"my-observability-service\", status=~\"4..|5..\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}