apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: "app"
  POSTGRES_PASSWORD: "app"
  POSTGRES_DB: "orders"
  DB_USER: "app"
  DB_PASSWORD: "app"
  DB_NAME: "orders"
